#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
"""
Installation script for excentury

To see usage run "python install -h".

"""

def run():
    """run install"""
    print "Oops ... haven't done this yet ..."
    print 'Use the temporary installation for now'

if __name__ == '__main__':
    run()
